# Generated by Django 3.2.16 on 2022-10-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('escola', models.CharField(max_length=255)),
                ('tipo', models.IntegerField(choices=[(0, 'EFG'), (1, 'COTEC'), (2, 'UDEPI'), (3, 'CVT'), (4, 'Salas de Extensão')])),
            ],
            options={
                'db_table': 'escolas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidade', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'EAD')])),
            ],
            options={
                'db_table': 'modalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(choices=[(0, 'Capacitação'), (1, 'Qualificação'), (2, 'Técnico'), (3, 'Superior')])),
            ],
            options={
                'db_table': 'tipo_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DivisaoDeMetasPorEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='DivisaoDeMetas.escola', verbose_name='Nome da escola')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DivisaoDeMetas.modalidade', verbose_name='Modalidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DivisaoDeMetas.tipocurso', verbose_name='Tipo')),
            ],
            options={
                'db_table': 'divisaodemetasporescola',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
