# Generated by Django 4.1.4 on 2023-01-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appprojeto1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisaoDeMetasPorEscola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ano",
                    models.IntegerField(
                        help_text="Ano de execução da meta", verbose_name="Ano"
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")],
                        help_text="Semestre de execução da meta",
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "carga_horaria",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Carga horária disponível",
                        verbose_name="Ch. disp.",
                    ),
                ),
                (
                    "carga_horaria_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Carga horária total",
                        verbose_name="Ch. total",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        help_text="Escola para execução da meta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="escolas",
                        to="appprojeto1.metas_escolas",
                        verbose_name="Nome da escola",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        help_text="Modalidade de execução do curso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="appprojeto1.metas_modalidade",
                        verbose_name="Modalidade",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        help_text="Tipo do curso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="appprojeto1.metas_tipo",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "db_table": "divisaodemetasporescola",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
    ]
