# Generated by Django 3.2.16 on 2022-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaodemetasporescola',
            name='semestre',
            field=models.IntegerField(choices=[(0, '1º Semestre'), (1, '2º Semestre')], default=0, verbose_name='Semestre'),
        ),
    ]
