# Generated by Django 3.2.16 on 2022-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0003_auto_20221025_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria',
            field=models.IntegerField(default=0, verbose_name='Carga hr. disp.'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='semestre',
            field=models.IntegerField(choices=[(0, ''), (0, '1º Semestre'), (1, '2º Semestre')], default=0, verbose_name='Semestre'),
        ),
    ]
