# Generated by Django 3.2.16 on 2022-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0009_auto_20221026_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria_total',
            field=models.IntegerField(default=0, help_text='Carga horária total', verbose_name='Ch. total'),
        ),
    ]
