# Generated by Django 3.2.16 on 2022-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0010_alter_divisaodemetasporescola_carga_horaria_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0, help_text='Carga horária disponível', verbose_name='Ch. disp.'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria_total',
            field=models.PositiveIntegerField(default=0, help_text='Carga horária total', verbose_name='Ch. total'),
        ),
    ]
