# Generated by Django 3.2.16 on 2022-10-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0004_auto_20221025_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], verbose_name='Semestre'),
        ),
    ]
