# Generated by Django 3.2.16 on 2022-10-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0005_alter_divisaodemetasporescola_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria',
            field=models.IntegerField(default=0, help_text='Carga horária disponível', verbose_name='Carga hr. disp.'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria_total',
            field=models.IntegerField(default=0, help_text='Carga horária total cadastrada', verbose_name='Carga hr. total'),
        ),
    ]
