# Generated by Django 3.2.16 on 2022-10-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0007_auto_20221025_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='escola',
            field=models.ForeignKey(help_text='Escola para execução da meta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='escolas', to='DivisaoDeMetas.escola', verbose_name='Nome da escola'),
        ),
    ]
