# Generated by Django 4.0.6 on 2023-10-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0023_metas_efg_origem_replan'),
        ('retificacao_edital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas_retificadas',
            name='origem_replan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appprojeto1.metas_efg'),
        ),
    ]
