# Generated by Django 4.0.6 on 2023-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retificacao_edital', '0002_alter_turmas_retificadas_origem_replan'),
    ]

    operations = [
        migrations.AddField(
            model_name='editais_retificados',
            name='saldo_disponivel',
            field=models.IntegerField(default=0),
        ),
    ]
