version: '3'

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            EFG_DOMAINS_HOST: ${EFG_DOMAINS_HOST}
            EFG_DOMAINS_PORT: ${EFG_DOMAINS_PORT}
            EFG_DOMAINS_USER: ${EFG_DOMAINS_USER}
            EFG_DOMAINS_DB: ${EFG_DOMAINS_DB}
            EFG_DOMAINS_PASS: ${EFG_DOMAINS_PASS}
            COTEC_DOMAINS_HOST: ${COTEC_DOMAINS_HOST}
            COTEC_DOMAINS_PORT: ${COTEC_DOMAINS_PORT}
            COTEC_DOMAINS_USER: ${COTEC_DOMAINS_USER}
            COTEC_DOMAINS_DB: ${COTEC_DOMAINS_DB}
            COTEC_DOMAINS_PASS: ${COTEC_DOMAINS_PASS}
            PRIMARY_DOMAIN_NAME: ${PRIMARY_DOMAIN_NAME}
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=backend"

            - "traefik.constraint-label-stack=projeto_cett"
            - "traefik.http.services.projeto_cett.loadbalancer.server.port=8000"
            #http
            - "traefik.http.routers.projeto_cett_http.rule=Host(`efg-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`) || Host(`cotec-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
            - "traefik.http.routers.projeto_cett_http.entrypoints=web"
            - "traefik.http.routers.projeto_cett_http.middlewares=https_redirect"
            #https
            - "traefik.http.routers.projeto_cett_https.rule=Host(`efg-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`) || Host(`cotec-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
            - "traefik.http.routers.projeto_cett_https.entrypoints=websecure"
            - "traefik.http.routers.projeto_cett_https.tls.certresolver=letsencryptresolver"

        volumes:
            - ./src:/home/python/app
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/Editais:/home/python/app/static/editais:rw
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/EFG/Editais:/home/python/app/static/EFG/editais:rw
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/COTEC/Editais:/home/python/app/static/COTEC/editais:rw

networks:
    default:
        external: true
        name: backend
