version: '3'

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            CAMUNDA_DOMAINS_HOST: ${CAMUNDA_DOMAINS_HOST}
            CAMUNDA_DOMAINS_PORT: ${CAMUNDA_DOMAINS_PORT}
            CAMUNDA_DOMAINS_USER: ${CAMUNDA_DOMAINS_USER}
            CAMUNDA_DOMAINS_DB: ${CAMUNDA_DOMAINS_DB}
            CAMUNDA_DOMAINS_PASS: ${CAMUNDA_DOMAINS_PASS}

        volumes:
            - ./src:/home/app/src
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/Editais:/home/app/src/static/editais:ro

networks:
    default:
        external: true
        name: backend
