version: '3'

services:
  dbadmin:
    extends:
      file: ./${APP_CONFIG_DIR}/${DB_ADM_NAME}/docker-compose.yml
      service: ${DB_ADM_NAME}
    container_name: ${DB_ADM_HOST}
    networks:
      - default
      - backend
