version: '3'

services:
    app:
        restart: always
        image: projeto-cett
        container_name: ${DJ_HOST}
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - APP_USER_NAME=${APP_USER_NAME}
                - APP_UID=${APP_UID}
                - APP_GID=${APP_GID}
                - APP_NAME=${APP_NAME}
        env_file:
            - .env
        environment:
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            CAMUNDA_URL: ${CAMUNDA_URL}
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            EFG_DOMAINS_HOST: ${EFG_DOMAINS_HOST}
            EFG_DOMAINS_PORT: ${EFG_DOMAINS_PORT}
            EFG_DOMAINS_USER: ${EFG_DOMAINS_USER}
            EFG_DOMAINS_DB: ${EFG_DOMAINS_DB}
            EFG_DOMAINS_PASS: ${EFG_DOMAINS_PASS}
            COTEC_DOMAINS_HOST: ${COTEC_DOMAINS_HOST}
            COTEC_DOMAINS_PORT: ${COTEC_DOMAINS_PORT}
            COTEC_DOMAINS_USER: ${COTEC_DOMAINS_USER}
            COTEC_DOMAINS_DB: ${COTEC_DOMAINS_DB}
            COTEC_DOMAINS_PASS: ${COTEC_DOMAINS_PASS}
            PRIMARY_DOMAIN_NAME: ${PRIMARY_DOMAIN_NAME}
        external_links:
            - ${DB_HOST}
        labels:
            #Enable Traefk 
            - "traefik.enable=true"
           
            - "traefik.http.services.${DJ_HOST}.loadbalancer.server.port=${DJ_PORT}"
            #http
            - "traefik.http.routers.${DJ_HOST}.service=${DJ_HOST}@docker"
            - "traefik.http.routers.${DJ_HOST}.rule=Host(`efg-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`) || Host(`cotec-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
            
        volumes:
            - ./src:/home/${APP_USER_NAME}/${APP_NAME}
            - ./backups:/home/${APP_USER_NAME}/${APP_NAME}/backups
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/Editais:/home/${APP_USER_NAME}/${APP_NAME}/static/editais:rw
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/EFG/Editais:/home/${APP_USER_NAME}/${APP_NAME}/static/EFG/editais:rw
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/COTEC/Editais:/home/${APP_USER_NAME}/${APP_NAME}/static/COTEC/editais:rw

networks:
    default:
        external: true
        name: proxy
