version: '3'

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            CAMUNDA_DOMAINS_HOST: ${CAMUNDA_DOMAINS_HOST}
            CAMUNDA_DOMAINS_PORT: ${CAMUNDA_DOMAINS_PORT}
            CAMUNDA_DOMAINS_USER: ${CAMUNDA_DOMAINS_USER}
            CAMUNDA_DOMAINS_DB: ${CAMUNDA_DOMAINS_DB}
            CAMUNDA_DOMAINS_PASS: ${CAMUNDA_DOMAINS_PASS}
        labels:
            - "traefik.enable=true"
            - "traefik.constraint-label-stack=projeto-efg"
            - "traefik.docker.network=backend"
            - "traefik.http.services.projeto-efg.loadbalancer.server.port=8000"
            #http
            - "traefik.http.routers.projeto-efg_http.rule=Host(`efg-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
            - "traefik.http.routers.projeto-efg_http.entrypoints=web"
            - "traefik.http.routers.projeto-efg_http.middlewares=https_redirect"
            #https
            - "traefik.http.routers.projeto-efg_https.rule=Host(`efg-index.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
            - "traefik.http.routers.projeto-efg_https.entrypoints=websecure"
            - "traefik.http.routers.projeto-efg_https.tls.certresolver=letsencryptresolver"
        volumes:
            - ./src:/home/app/src
            - ${ACS_DOCS_PATH}/Ensino/gerarEdital/Editais:/home/app/src/static/editais:ro

networks:
    default:
        external: true
        name: backend
