version: '3.4'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    volumes:
      - ./src:/home/appuser/app:rw
    ports:
     - 8000:8000

networks:
   default:
     external: true
     name: backend
