# Generated by Django 4.0.6 on 2022-08-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0003_metas_efg_alter_solicitacao_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitacao',
            table=None,
        ),
    ]
