"""
Django settings for projeto1 project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%7515@+#n10+#rskbff7_5&g1smjc8j!yn%g3(@eh1yt@p#rpf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [ 
    'https://*.cett.org.br', 
    'http://*.cett.org.br',
    'https://*.cett.dev.br', 
    'http://*.cett.dev.br',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appprojeto1',
    'SolicitacaoDeTurmas.apps.SolicitacaodeturmasConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    # 'django_select2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto1.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Tell select2 which cache configuration to use:
# SELECT2_CACHE_BACKEND = "select2"
# SELECT2_THEME = 'default'

WSGI_APPLICATION = 'projeto1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.mysql',
        'NAME': 'c1camundadb',
        'USER': 'c1camundadb',
        'HOST': '200.137.215.67',
        'PASSWORD': 'iC7@hdDF',
        'PORT': '3306',

        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    },
    
    # 'siga': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'c3siga',
    #     'USER': 'consulta',
    #     'HOST': 'siga-ser.cotec.org.br',
    #     'PASSWORD': '4rVqoiDp9ahwEqqMtP49Fi',
    #     'PORT': '3306',
    #     'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    # },
    
    # 'camunda': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'c35camundadb',
    #     'USER': 'c35camundadb',
    #     'HOST': 'isp.cett.dev.br',
    #     'PASSWORD': 'iC7@hdDF',
    #     'PORT': '3306',

    #     'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    # },
}

# DATABASE_ROUTERS = ['appprojeto1.dbrotas.EixosRota','appprojeto1.dbrotas.CamundaRota']

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = False

DATE_INPUT_FORMATS = '%d/%m/%Y'
DATETIME_INPUT_FORMATS = ['%d/%m/%Y']
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
