# Generated by Django 4.1.4 on 2023-01-17 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cadastrar_curso",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("curso", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("escolaridade", models.CharField(max_length=255)),
                ("idade_min", models.IntegerField()),
                ("carga_horaria", models.IntegerField()),
                ("siga_id", models.IntegerField()),
            ],
            options={
                "db_table": "cursos",
                "ordering": ("curso",),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Curso_escola",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("escola_id", models.IntegerField()),
                ("curso_id", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "curso_escola",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cursos",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("id_eixos", models.IntegerField()),
                ("tipo", models.IntegerField()),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "qualificacoes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Edital",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("num_edital", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("dt_ini_edit", models.DateField(blank=True, null=True)),
                ("dt_fim_edit", models.DateField(blank=True, null=True)),
                ("dt_ini_insc", models.DateField(blank=True, null=True)),
                ("dt_fim_insc", models.DateField(blank=True, null=True)),
                ("status", models.CharField(max_length=255)),
                ("pdf", models.CharField(max_length=255)),
                ("motivo", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "edital_ensino",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Eixos",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("eixo_id", models.IntegerField()),
                ("nome", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "eixos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Item_apoiado",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("id_rubrica", models.IntegerField()),
                ("item_apoiado", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "item_apoiado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_descricoes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "descricao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_escolas",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("escola", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[
                            (0, "EFG"),
                            (1, "COTEC"),
                            (2, "UDEPI"),
                            (3, "CVT"),
                            (4, "Salas de Extensão"),
                        ]
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("telefone", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "db_table": "escolas",
                "ordering": ("escola",),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_modalidade",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("modalidade", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "modalidade",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_tipo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tipo_curso",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_trimestre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("trimestre", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "trimestre",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Rubrica",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("rubrica", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "rubrica",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("eixo", models.CharField(max_length=255)),
                ("curso", models.CharField(max_length=255)),
                ("modalidade", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=255)),
                ("justificativa", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "appprojeto1_solicitacao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Unidades",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("und", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "unidade",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Users_ids",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_selecao_id", models.IntegerField()),
                ("user_siga_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_siga_selecao",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User_permission",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("permission", models.CharField(max_length=255)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_escolas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_permission",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Udepi_municipio",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("municipio", models.CharField(max_length=255)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_escolas",
                    ),
                ),
            ],
            options={
                "db_table": "udepi_municipio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Orcamento_plano_trabalho",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
                ("und", models.CharField(max_length=255)),
                ("qtd_global", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "valor_medio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("valor_global", models.DecimalField(decimal_places=2, max_digits=15)),
                ("custeio", models.DecimalField(decimal_places=2, max_digits=15)),
                ("capital", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "item_apoiado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.item_apoiado",
                    ),
                ),
                (
                    "rubrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.rubrica",
                    ),
                ),
            ],
            options={
                "db_table": "planejamento_trabalho",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_sinteticas",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("diretoria", models.CharField(max_length=255)),
                ("ano", models.IntegerField()),
                ("ch_ofertada", models.IntegerField()),
                ("vagas", models.IntegerField()),
                ("repasse", models.FloatField()),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_tipo",
                    ),
                ),
                (
                    "descricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_descricoes",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_escolas",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_modalidade",
                    ),
                ),
            ],
            options={
                "db_table": "Metas_sinteticas_efg",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metas_efg",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "diretoria",
                    models.CharField(
                        choices=[("DAC", "DAC"), ("DDA", "DDA"), ("DE", "DE")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MATUTINO", "MATUTINO"),
                            ("VESPERTINO", "VESPERTINO"),
                            ("NOTURNO", "NOTURNO"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("ano", models.IntegerField()),
                (
                    "trimestre",
                    models.IntegerField(
                        choices=[(1, "1º SEMESTRE"), (2, "2º SEMESTRE")], null=True
                    ),
                ),
                ("vagas_totais", models.IntegerField(null=True)),
                ("carga_horaria", models.IntegerField(null=True)),
                ("carga_horaria_total", models.IntegerField(null=True)),
                ("previsao_inicio", models.DateField(null=True)),
                ("previsao_fim", models.DateField(null=True)),
                ("dias_semana", models.CharField(max_length=255)),
                ("previsao_abertura_edital", models.DateField(blank=True, null=True)),
                ("previsao_fechamento_edital", models.DateField(blank=True, null=True)),
                ("data_registro", models.DateField(blank=True, null=True)),
                (
                    "situacao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Aguardando Análise"),
                            (1, "Reprovado"),
                            (2, "Em Análise"),
                            (3, "Aprovado"),
                            (4, "Edital gerado"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "jus_reprovacao",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.cadastrar_curso",
                    ),
                ),
                (
                    "eixo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.eixos",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_escolas",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_modalidade",
                    ),
                ),
                (
                    "num_edital",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.edital",
                    ),
                ),
                (
                    "tipo_curso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.metas_tipo",
                    ),
                ),
                (
                    "udepi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appprojeto1.udepi_municipio",
                    ),
                ),
            ],
            options={
                "db_table": "Turmas_planejado_orcado",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="eixos",
            name="escola",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appprojeto1.metas_escolas",
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="escola",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appprojeto1.metas_escolas",
            ),
        ),
        migrations.AddField(
            model_name="cadastrar_curso",
            name="eixos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appprojeto1.eixos"
            ),
        ),
        migrations.AddField(
            model_name="cadastrar_curso",
            name="escola",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appprojeto1.metas_escolas",
            ),
        ),
        migrations.AddField(
            model_name="cadastrar_curso",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appprojeto1.metas_modalidade",
            ),
        ),
        migrations.AddField(
            model_name="cadastrar_curso",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appprojeto1.metas_tipo"
            ),
        ),
    ]
