# Generated by Django 4.1.5 on 2023-01-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrar_curso",
            name="eixos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appprojeto1.eixos",
            ),
        ),
    ]
