# Generated by Django 4.0.6 on 2022-08-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0002_auto_20221108_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas_efg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diretoria', models.CharField(max_length=255)),
                ('escola', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('modalidade', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('dias_semana', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('carga_horaria_total', models.IntegerField()),
                ('repasse', models.FloatField()),
                ('valor_unitario', models.FloatField()),
            ],
        ),
        migrations.AlterModelTable(
            name='solicitacao',
            table='appprojeto1_solicitacao',
        ),
    ]
