# Generated by Django 4.1.5 on 2023-01-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0003_alter_user_permission_escola_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_permission",
            name="escola",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="appprojeto1.metas_escolas",
            ),
        ),
    ]
