# Generated by Django 4.1.5 on 2023-01-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0004_alter_user_permission_escola"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursos",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
