# Generated by Django 4.0.6 on 2022-08-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0005_alter_cursos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cursos',
            table='qualificacoes',
        ),
        migrations.AlterModelTable(
            name='solicitacao',
            table='appprojeto1_solicitacao',
        ),
    ]
