# Generated by Django 4.1.5 on 2023-01-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0006_alter_cadastrar_curso_id_alter_curso_escola_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrar_curso",
            name="siga_id",
            field=models.IntegerField(null=True),
        ),
    ]
