# Generated by Django 4.1.5 on 2023-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0007_alter_cadastrar_curso_siga_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrar_curso",
            name="carga_horaria",
            field=models.IntegerField(null=True),
        ),
    ]
