# Generated by Django 4.1.5 on 2023-01-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appprojeto1", "0008_alter_cadastrar_curso_carga_horaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edital",
            name="motivo",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
