# Generated by Django 4.1.5 on 2023-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appprojeto1", "0009_alter_edital_motivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="metas_efg",
            name="curso_tecnico",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="metas_efg",
            name="qualificacoes",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="users_ids",
            name="cpf",
            field=models.CharField(default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="metas_efg",
            name="turno",
            field=models.CharField(
                choices=[
                    ("MATUTINO", "MATUTINO"),
                    ("VESPERTINO", "VESPERTINO"),
                    ("NOTURNO", "NOTURNO"),
                    ("INTEGRAL", "INTEGRAL"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
