# Generated by Django 4.1.5 on 2023-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appprojeto1",
            "0010_metas_efg_curso_tecnico_metas_efg_qualificacoes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metas_efg",
            name="qualificacoes",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
