# Generated by Django 4.0.6 on 2023-04-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appprojeto1', '0013_edital_user_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='user_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
