# Generated by Django 4.1.5 on 2023-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appprojeto1", "0015_alter_edital_user_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="metas_escolas",
            name="selecao_id",
            field=models.IntegerField(null=True),
        ),
    ]
