# Generated by Django 4.1.5 on 2023-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appprojeto1", "0016_metas_escolas_selecao_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metas_escolas",
            name="selecao_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
