# Generated by Django 4.0.6 on 2023-08-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0017_alter_metas_escolas_selecao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas_efg',
            name='situacao',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Análise'), (1, 'Reprovado'), (2, 'Em Análise'), (3, 'Aprovado'), (4, 'Edital gerado'), (5, 'Replanejado')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='Saldo_replanejamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appprojeto1.metas_modalidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appprojeto1.metas_tipo')),
            ],
            options={
                'db_table': 'saldo_replanejamento',
                'managed': True,
            },
        ),
    ]
