# Generated by Django 4.0.6 on 2023-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0018_alter_metas_efg_situacao_saldo_replanejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo_replanejamento',
            name='saldo',
            field=models.IntegerField(),
        ),
    ]
