# Generated by Django 4.0.6 on 2023-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0019_alter_saldo_replanejamento_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo_replanejamento',
            name='ano',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='saldo_replanejamento',
            name='semestre',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='saldo_replanejamento',
            name='saldo',
            field=models.IntegerField(default=None),
        ),
    ]
