# Generated by Django 4.0.6 on 2023-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0022_saldo_replanejamento_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas_efg',
            name='origem_replan',
            field=models.IntegerField(null=True),
        ),
    ]
