# Generated by Django 3.2.16 on 2022-11-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprojeto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas_efg',
            name='num_edital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metas_efg',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Aguardando Análise'), (1, 'Aprovado'), (2, 'Reprovado')], default=0),
        ),
    ]
