# Generated by Django 3.2.16 on 2022-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0002_divisaodemetasporescola_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisaodemetasporescola',
            name='carga_horaria_total',
            field=models.IntegerField(default=0, verbose_name='Carga hr. total'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga hr. disp.'),
        ),
    ]
