# Generated by Django 3.2.16 on 2022-10-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DivisaoDeMetas', '0006_auto_20221025_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='ano',
            field=models.IntegerField(help_text='Ano de execução da meta', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='modalidade',
            field=models.ForeignKey(help_text='Modalidade de execução do curso', on_delete=django.db.models.deletion.DO_NOTHING, to='DivisaoDeMetas.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], help_text='Semestre de execução da meta', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='divisaodemetasporescola',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo do curso', on_delete=django.db.models.deletion.DO_NOTHING, to='DivisaoDeMetas.tipocurso', verbose_name='Tipo'),
        ),
    ]
